// react-class-todos/src/components/Home.jsx
import React, { Component } from 'react';
import AddForm from './AddForm'
import Table from './Table'
import EditForm from './EditForm'

export default class Home extends Component{

    state = {
        todos:[],
        editedTodo: {},
        editing : false
    };

    async componentDidMount(){
        try {
            const res = await fetch("/api/todos")
            .then((r) => r.json());
            this.setState({todos: res.todos})
          } catch (e) {
            console.log(e);
            return;
        }
    }

    addTodoItem = todo => {

        const sendTodo = async () => {
            try{
                const res = await fetch("/api/todos", {
                    method: "POST",
                    body: JSON.stringify(todo),
                    headers: {
                    "Content-type": "application/json; charset=UTF-8",
                    },
                }).then((r) => r.json());
                this.setState({
                    todos: [...this.state.todos, res.todo],
                    editing:false
                })

                return;
            }catch(e){
                console.log(e);
                return;
            }
        };

        sendTodo();
        return;
    };

    getEditTodo = data => {

        const editTodo = {
            id: data.id,
            text: data.text,
        };
        this.setState({
            editing:true,
            editedTodo: editTodo
        // }, ()=>{console.log(this.state.editedTodo, this.state.editing)});
        });
        // console.log("Todo #", data.todo.id, "is clicked");
    }
    
    updateTodo = (editedTodo) => {
       const emendTodo = async () => {
            try {
                await fetch(`/api/todos/${editedTodo.id}`, {
                    method: "PATCH",
                    body: JSON.stringify(editedTodo),
                    headers: {
                        "Content-type": "application/json; charset=UTF-8",
                    },
                }).then((r) => r.json());

                const editTodo = [...this.state.todos.map((todo)=>(todo.id === editedTodo.id?editedTodo:todo))];
                this.setState({
                    todos:editTodo,
                    editing:false
                });
                return;
            } catch (e) {
                console.log(e);
                return;
            }
        };
        emendTodo();
    }

    delTodo = id => {
        const delTodo = async () => {
            try {
                await fetch(`/api/todos/${id}`, {
                method: "DELETE",
                });
                this.setState({
                    todos: [
                        ...this.state.todos.filter(todo => {
                            return todo.id !== id;
                        })
                    ],
                    editing:false
                });
            } catch (e) {
                console.log(e);
            }
       };
       delTodo();
    };

    render(){
        return(
            <div className="columns is-centered">
                <div className="column is-5-tablet is-10-mobile">
                    <div className="card">
                        <header className="header">
                            <p className="card-header-title heading">
                                Todos
                            </p>
                        </header>
                        <div className="card-content">
                        {this.state.editing ? (
                            <EditForm editing={this.state.editing} 
                                editedTodo={this.state.editedTodo} 
                                updateTodoProps={this.updateTodo}
                            />
                        ) : (
                            <AddForm addTodoProps={this.addTodoItem}/>
                        )}
                        <hr />
                            {
                                this.state.todos.length<1?
                                <div className="loader"></div>
                                :
                                <Table todos={this.state.todos} getEditTodoProps={this.getEditTodo} deleteTodoProps={this.delTodo}/>
                            }
                        </div>
                    </div>
                </div>
            </div>  
        )
    }
}

// vue-todos/src/pages/Home.vue
<template>
  <div>
    <div class="card">
      <header class="header">
        <p class="card-header-title heading">Todos</p>
      </header>
      <div class="card-content">
        <todo-form @add-todo="postTodo" :editedTodo="editedTodo" :editing="editing"/>
        <hr />
        <todo-table :todos="todos" @edit-todo="editTodo" @delete-todo="deleteTodo"/>
      </div>
    </div>
  </div>
</template>

<style scoped>
.heading {
  font-size: 1.5rem;
}
</style>

<script>
// import axios from "axios";
import TodoTable from "../components/TodoTable.vue";
import TodoForm from "../components/TodoForm.vue";
export default {
  name: "Todos",
  components: {
    TodoForm,
    TodoTable,
  },
  created() {
    this.getTodos();
  },
  data() {
    return {
      todos: [],
      newTodo: {},
      editedTodo: {},
      editing: false,
    };
  },
  methods: {
    async getTodos() {
      try {
        // let res = await axios.get(`/api/todos`);
        // this.todos = res.data.todos;
        const res = await fetch(`api/todos`).then((r) => r.json());
        this.todos = res.todos;
      } catch (e) {
        console.log(e);
        return { todos: [] };
      }
    },
    // delete todo
    async deleteTodo(id) {
      try {
        // await axios.delete(`/api/todos/${id}`); // delete todo
        await fetch(`/api/todos/${id}`, {
          method: "DELETE",
        });
        this.todos = this.todos.filter((todo) => todo.id !== id);
        // this.getTodos();
      } catch (e) {
        console.log(e);
        return;
      }
    },
    // set editing mode
    editTodo(todo) {
      this.editing=true;
      this.editedTodo = { ...todo };
    },
    // add or edit todo
    async postTodo(todo) {
        if(todo.text){
            if(todo.id){
                try {
                // let res = await axios.patch(`/api/todos/${id}`, {
                //   data: this.editedTodo,
                // });
                // this.getTodos();
                    const res = await fetch(`/api/todos/${todo.id}`, {
                    method: "PATCH",
                    body: JSON.stringify(todo),
                    headers: {
                        "Content-type": "application/json; charset=UTF-8",
                    },
                    }).then((r) => r.json());
                    // this.getTodos();
                    const info = res.todo;
                    this.todos = this.todos.map((todos) =>
                        todos.id === todo.id ? info : todos
                    );
                    this.editing=false;
                    return;
                } catch (e) {
                    console.log(e);
                    return;
                }
            }else{
                try {
                    // let res = await axios.post(`/api/todos`, {
                    //   data: this.newTodo,
                    // });
                    // this.todos.push(res.data.todo);
                    // this.todos = [...this.todos, res.data.todo]
                    const res = await fetch("/api/todos", {
                        method: "POST",
                        body: JSON.stringify(todo),
                        headers: {
                        "Content-type": "application/json; charset=UTF-8",
                        },
                    }).then((r) => r.json());
                    // console.log(res.todo);
                    this.todos = [...this.todos, res.todo];
                    return;
                } catch (e) {
                    console.log(e);
                    return;
                }
            }
        }else{
            console.log("Field is empty");
            return;
        }
    },
  },
};
</script>
