// angular-todos/src/app/components/home/home.component.ts
// import { Router } from '@angular/router';
import { ApiService } from './../../services/api.service';
import { Component, OnInit } from '@angular/core';
import { Todo } from '../../model/Todo.model';
import { FormGroup, FormBuilder, Validators } from "@angular/forms";

@Component({
  selector: 'home-component',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  todos: Todo[]=[];
  editing:boolean=false;
  editTodo={}

  submitted = false;
  todoForm: FormGroup;
  
  constructor(
    public fb: FormBuilder,
    // private router: Router,
    private apiService: ApiService
  ) { 
    this.mainForm();
    this.readTodos();
  }

  ngOnInit():void { }

  mainForm():void {
    this.todoForm = this.fb.group({
      id: [''],
      text: ['', [Validators.required]],
    })
  }

  // Getter to access form control
  get myForm(){
    return this.todoForm.controls;
  }

  /*
  onSubmit():void|boolean {
    this.submitted = true;
    if (!this.todoForm.valid) {
      return false;
    } else {
      if(this.editing===false){
        let info = {text:this.todoForm.get('text').value}
        this.apiService.createTodo(info).subscribe(
          (res:any) => {
            console.log('Todo successfully created!')
            this.todos = [...this.todos, res.todo];
            this.todoForm.setValue({
            id:"",
            text: "",
           })
          }, (error) => {
            console.log(error);
          });
      }else{

        this.apiService.updateTodo(this.todoForm.value)
        .subscribe((res:any) => {
          console.log('Todo updated successfully!')
          const info = res.todo;
          this.todos = this.todos.map((todo) =>
            todo.id === this.todoForm.value.id ? info : todo
          );
          this.todoForm.setValue({
            id:"",
            text: "",
           })
        }, (error) => {
          console.log(error)
        })
      }
    }
  }
  */

  async onSubmit() {
    this.submitted = true;
    if (!this.todoForm.valid) {
      return false;
    } else {
      if(this.editing===false){

        try{
          let info = {text:this.todoForm.get('text').value}

          let res:any = await this.apiService.createTodo(info).toPromise();
          console.log('Todo successfully created!')
          this.todos = [...this.todos, res.todo];
          this.todoForm.setValue({
            id:"",
            text: "",
          })
          return;
        }
        catch(e){
          console.log(e);
          return;
        }
      }else{

        try {
          const res:any = await this.apiService.updateTodo(this.todoForm.value).toPromise();
          console.log('Todo updated successfully!')
          const info = res.todo;
          this.todos = this.todos.map((todo) =>
            todo.id === this.todoForm.value.id ? info : todo
          );
          this.todoForm.setValue({
            id:"",
            text: "",
           })
           return;
        } catch (e) {
          console.log(e);
          return;
        }
      }
    }
  }

  readTodos():void{
    this.apiService.getTodos().subscribe((res:any) => {
      this.todos = res.todos;
    })    
  }

  setEditMode(todo) {
    this.editing = true;
    this.editTodo = { ...todo };
    this.todoForm.setValue({
      id: todo.id,
      text: todo.text,
     });
  }

  /*
  removeTodo(todo:Todo):void {
    if(window.confirm('Are you sure?')) {
        this.apiService.deleteTodo(todo.id).subscribe((res) => {
            this.todos = this.todos.filter(t => t.id !== todo.id);
          }
        )  
    }
  }
  */

  async removeTodo(todo:Todo){
    try {
      await this.apiService.deleteTodo(todo.id);
      this.todos = this.todos.filter(t => t.id !== todo.id);
    } catch (e) {
      console.log(e);
      return;
    }
  }
}

<div class="card">
  <header class="header">
    <p class="card-header-title heading">Todos</p>
  </header>
  <div class="card-content">
    <!-- <div v-if="editing === false"> -->
      <!-- <form [formGroup]="employeeForm" (ngSubmit)="onSubmit()"> -->
      <form [formGroup]="todoForm" (ngSubmit)="onSubmit()">
        <div class="field has-addons has-addons-centered">
          <div class="control">
            <input class="input" type="hidden" formControlName="id"/>
            <input class="input" type="text" placeholder="Add todo..." formControlName="text"/>
          </div>
          <div class="control" [hidden]="editing">
            <button class="button is-primary">
              <span class="icon is-small">
                <img height="32" width="32" src="/add-circle-outline.svg" />
              </span>
            </button>
          </div>
          <div class="control" [hidden]="!editing">
            <button class="button is-warning">
              <span class="icon is-small">
                <img height="32" width="32" src="/create-outline.svg" />
              </span>
            </button>
          </div>
        </div>
      </form>
    <!-- </div> -->
    <!-- <div v-else>
      <form @submit.prevent="postEdit">
        <input :value="editedTodo.id" type="hidden" />
        <div class="field has-addons has-addons-centered">
          <div class="control">
            <input
              v-model="editedTodo.text"
              class="input"
              type="text"
              placeholder="Update todo..."
            />
          </div>
          <div class="control">
            <button class="button is-warning">
              <span class="icon is-small">
                <img height="32" width="32" src="../assets/img/edit-icon.svg" />
              </span>
            </button>
          </div>
        </div>
      </form> -->

      <!--
      <p>Editing ...</p>
      -->
    <!-- </div> -->

    <hr />
    <ul>
      <!-- <li v-if="todos.length < 1">
        <Spinner></Spinner>
      </li> -->
      <!-- <li v-else class="list-item" v-for="todo in todos" :key="todo.id">
        <div class="is-flex" style="align-items: center;">
          <span class="is-pulled-left">{{ todo.text }}</span>
          <div style="flex: 1;"></div>
          <button
            class="button is-text is-pulled-right is-small is-warning"
            @click="editTodo(todo)"
          >
            <span class="icon">
              <img height="32" width="32" src="../assets/img/edit-icon.svg" />
            </span>
          </button>
          &nbsp;
          <button
            class="button is-text is-pulled-right is-small is-danger"
            @click="deleteTodo(todo.id)"
          >
            <span class="icon">
              <img height="32" width="32" src="../assets/img/trash-icon.svg" />
            </span>
          </button>
        </div>
      </li> -->
      <li *ngIf="todos.length === 0">
        No todos !
      </li>
      <ng-container *ngIf="todos.length!==0">
        <li class="list-item" *ngFor="let todo of todos">
          <div class="is-flex" style="align-items: center;">
            <span class="is-pulled-left">{{ todo.text }}</span>
            <div style="flex: 1;"></div>
            <button
              class="button is-text is-pulled-right is-small is-warning"
              (click)="setEditMode(todo)"
            >
              <span class="icon">
                <img height="32" width="32" src="/create-outline.svg" />
              </span>
            </button>
            &nbsp;
            <button
              class="button is-text is-pulled-right is-small is-danger"
              (click)="removeTodo(todo)"
            >
              <span class="icon">
                <img height="32" width="32" src="/trash-outline.svg" />
              </span>
            </button>
          </div>
        </li>
      </ng-container>
    </ul>
  </div>
</div>

// vue-todos/src/pages/Home.vue
<template>
  <div>
    <div class="card">
      <header class="header">
        <p class="card-header-title heading">Todos</p>
      </header>
      <div class="card-content">
        <div v-if="editing === false">
          <form @submit.prevent="postTodo">
            <div class="field has-addons has-addons-centered">
              <div class="control">
                <input v-model="newTodo.text" class="input" type="text" placeholder="Add todo..." />
              </div>
              <div class="control">
                <button class="button is-primary">
                  <span class="icon is-small">
                    <img height="32" width="32" src="../assets/img/plus-icon.svg" />
                  </span>
                </button>
              </div>
            </div>
          </form>
        </div>
        <div v-else>
          <form @submit.prevent="postEdit">
            <input :value="editedTodo.id" type="hidden" />
            <div class="field has-addons has-addons-centered">
              <div class="control">
                <input
                  v-model="editedTodo.text"
                  class="input"
                  type="text"
                  placeholder="Update todo..."
                />
              </div>
              <div class="control">
                <button class="button is-warning">
                  <span class="icon is-small">
                    <img height="32" width="32" src="../assets/img/edit-icon.svg" />
                  </span>
                </button>
              </div>
            </div>
          </form>

          <!--
          <p>Editing ...</p>
          -->
        </div>

        <hr />
        <ul>
          <li v-if="todos.length < 1">
            <Spinner></Spinner>
          </li>
          <li v-else class="list-item" v-for="todo in todos" :key="todo.id">
            <div class="is-flex" style="align-items: center;">
              <span class="is-pulled-left">{{ todo.text }}</span>
              <div style="flex: 1;"></div>
              <button
                class="button is-text is-pulled-right is-small is-warning"
                @click="editTodo(todo)"
              >
                <span class="icon">
                  <img height="32" width="32" src="../assets/img/edit-icon.svg" />
                </span>
              </button>
              &nbsp;
              <button
                class="button is-text is-pulled-right is-small is-danger"
                @click="deleteTodo(todo.id)"
              >
                <span class="icon">
                  <img height="32" width="32" src="../assets/img/trash-icon.svg" />
                </span>
              </button>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<style scoped>
.top {
  margin-top: 0.5rem;
}
.heading {
  font-size: 1.5rem;
}
</style>

<script>
// import axios from "axios";
import Spinner from "../components/Spinner.vue";
export default {
  name: "Todos",
  components: {
    Spinner,
  },
  created() {
    // this.isLoading = true
    this.getTodos();
  },
  data() {
    return {
      todos: [],
      newTodo: {},
      editedTodo: {},
      editing: false,
      isLoading: false,
    };
  },
  methods: {
    async getTodos() {
      try {
        // let res = await axios.get(`/api/todos`);
        // this.todos = res.data.todos;
        const res = await fetch(`api/todos`).then((r) => r.json());
        this.todos = res.todos;
      } catch (e) {
        console.log(e);
        return { todos: [] };
      }
    },
    // add todo
    async postTodo() {
      if (this.newTodo.text) {
        try {
          // let res = await axios.post(`/api/todos`, {
          //   data: this.newTodo,
          // });
          // this.todos.push(res.data.todo);
          // this.todos = [...this.todos, res.data.todo]
          const res = await fetch("/api/todos", {
            method: "POST",
            body: JSON.stringify(this.newTodo),
            headers: {
              "Content-type": "application/json; charset=UTF-8",
            },
          }).then((r) => r.json());
          // console.log(res.todo);
          this.todos = [...this.todos, res.todo];
          this.newTodo = {};
          return;
        } catch (e) {
          console.log(e);
          return;
        }
      }
      console.log("Field is empty");
      return;
    },
    // delete todo
    async deleteTodo(id) {
      try {
        // await axios.delete(`/api/todos/${id}`); // delete todo
        await fetch(`/api/todos/${id}`, {
          method: "DELETE",
        });
        this.todos = this.todos.filter((todo) => todo.id !== id);
        // this.getTodos();
      } catch (e) {
        console.log(e);
        return;
      }
    },
    // set editing mode
    editTodo(todo) {
      this.editing = true;
      this.editedTodo = { ...todo };
    },
    // update todo in backend
    async postEdit() {
      this.editing = false;
      if (this.editedTodo.text) {
        const id = this.editedTodo.id;
        try {
          // let res = await axios.patch(`/api/todos/${id}`, {
          //   data: this.editedTodo,
          // });
          // this.getTodos();
            const res = await fetch(`/api/todos/${this.editedTodo.id}`, {
              method: "PATCH",
              body: JSON.stringify(this.editedTodo),
              headers: {
                "Content-type": "application/json; charset=UTF-8",
              },
            }).then((r) => r.json());
            // this.getTodos();
            const info = res.todo;
            this.todos = this.todos.map((todo) =>
              todo.id === this.editedTodo.id ? info : todo
            );
            this.editedTodo = {};
            return;
        } catch (e) {
          console.log(e);
          return;
        }
      }
      console.log("Field is empty");
      this.editedTodo = {};
      return;
    },
  },
};
</script>
