// react-hooks-todos/src/components/App.jsx
import React from 'react'
import Home from './Home'
import About from './About'
import Navigation from './Navigation'
import { BrowserRouter as Router, Switch, Route} from 'react-router-dom';

function App() {

  return (
    <Router>
        <Navigation/>
        <Switch>
            <Route exact path='/' component={Home} />
            <Route exact path='/about' component={About} />
        </Switch>
    </Router>
  )
}

export default App

// svelte-todos/src/app.svelte
<script>
  import { Route } from "tinro";
  import Home from "./components/home.svelte";
  import About from "./components/about.svelte";
  import Navigation from "./components/navigation.svelte";
</script>

<main>
  <Navigation />
  <div class="row is-center">
    <div class="col-10 col-5-md">
      <Route path="/">
        <Home />
      </Route>
      <Route path="/about">
        <About />
      </Route>
    </div>
  </div>
</main>
