// react-class-todos/src/components/Navigation.jsx
import React from 'react'
import { NavLink } from 'react-router-dom';

export default function Navigation(){
    return(
        <div className="row is-center">
            <div className="col">
                <nav className="tabs is-center">
                    <NavLink exact activeClassName="selectedNav" to={'/'}>Home</NavLink>
                    <NavLink exact activeClassName="selectedNav" to={'/about'}>About</NavLink>
                </nav>
            </div>
        </div>
    )
}

// vue-todos/src/components/Navigation.vue
<template>
  <div class="row is-center">
    <div class="col">
        <nav class="tabs is-center">
            <router-link to="/">Home</router-link>
            <router-link to="/about">About</router-link>
        </nav>
    </div>
  </div>
</template>

<script>
export default {
  name: "Navigation",
};
</script>

<style>
nav a.router-link-exact-active {
   border-color: #14854f;
}
</style>
